name: GitHub metrics as SVG image
on:
  # Schedule the metrics update
  schedule: [{cron: "0 * * * *"}]
  # (optional) Force update a commit occurs on master branch
  # All commits tagged with [Skip GitHub Action] will be ignored by this GitHub action
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_PRIVATE }}
          committer_token: ${{ secrets.METRICS_BOT }}
          filename: github-metrics.svg
          template: classic
          config_timezone: Europe/Zurich
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_traffic: yes
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          plugin_projects: yes
          plugin_projects_limit: 4
          debug: no
